config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  resources :pokemons do
    resources :masters
  end

  resources :masters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :jobs
    validates :character, presence: true, length: { minimum: 5}
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :song
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :character
end

app/models/master.rb
class Master < ApplicationRecord
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :master
end

app/models/pokemon_master.rb
class PokemonMaster < ApplicationRecord
  has_many :pokemon
end

app/models/pokemonmaster.rb
class Pokemonmaster < ApplicationRecord
  belongs_to :pokemon
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :genre
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def new
    @songs = Song.all
  end

  def create
    @genre = Genre.new(genre_params)

    @genre.save
    redirect_to @genre
  end

  def show
    @genres = Genre.find([params[:id]])
    render "index"
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to @genre
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

private

  def genre_params
    params.require(:genre).permit(:name, :description)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    def create
        @character = Character.find(params[:character_id])
        @job = @character.jobs.create(job_params)
        redirect_to character_path(@character)
    end

    def destroy
        @character = Character.find(params[:character_id])
        @job = @character.jobs.find(params[:id])
        @job.destroy

        redirect_to character_path(@character)
    end

    private
        def job_params
            params.require(:job).permit(:job_name , :job_level , :job_img)
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end

 
end

app/controllers/master_controller.rb
class MasterController < ApplicationController

  def index
    @masters = Master.all
  end

  def new
    @pokemons = Pokemon.all
    #renders new.html.erb in views folder because they have the same name
  end
  
  def show
    @masters = Master.find(params[:id])
    #cases when trying to get a master for the pokemon that does not exist

    if(parmams[:pokemon_id].to_i != @master.pokemon.id)
      puts "master does not exists"
    end
  end

  def create
    @master = Master.new(master_params)

    @master.save
    redirect_to master_index_path
  end

  def update
    @master = Master.find(params[:id])

    @master.update(master_params)
    redirect_to master_index_path

  end

  def edit
    @master = Master.find(params[:id])
    @pokemons = Pokemon.all

  end

  def destroy
    @master = Master.find(params[:id])

    @master.destroy
    redirect_to master_index_path
  end

  private

  def master_params
    params.require(:master).permit(:name, :pokemon_id)
  end

end  

app/controllers/masters_controller.rb
class MastersController < ApplicationController

    def index
        if params.has_key?(:pokemon_id)
            @masters = Master.where(pokemon_id: params[:pokemon_id])
            @pokemon = Pokemon.find(params[:pokemon_id])
        else
            @masters = Master.all.order("id ASC")
        end
    end

    def show
        @master = Master.find(params[:id])
        @pokemon = Pokemon.find(@master[:pokemon_id])
    end

    def new
        @master = Master.new
        @pokemons = Pokemon.all.order("id ASC")
    end

    def create
        @master = Master.create(master_params)
        redirect_to masters_path
	end
	
	def edit
		@master = Master.find(params[:id])
		@pokemons = Pokemon.all.order("id ASC")
	end

	def update
		@master = Master.find(params[:id])
		@master.update(master_params)
		redirect_to @master
	end

	def destroy
		@master = Master.find(params[:id])
		@master.destroy
		redirect_to masters_path
	end
	
    private def master_params
        params.require(:master).permit(:name, :pokemon_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :find_song, only: [:show, :edit, :update, :destroy]

  def index
    if params.has_key?(:genre_id)
      @songs = Song.where(genre_id: params[:genre_id])
    else
      @songs = Song.all
    end
  end

  def new
    @genres = Genre.all
  end

  def create
    @song = Song.new(song_params)

    @song.save
    redirect_to @song
  end

  def show
    @songs = Song.find([params[:id]])
    render "index"
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to @genre
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

private

  def song_params
    params.require(:song).permit(:name, :genre_id)
  end

  def find_song
    @song = Song.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/genres/edit.html.erb
<div class="container">

	<h5>Edit genre</h5>

	<%= form_with model: @genre, local: true do |f| %>

		<div class="form-group">
			<%= f.label(:name, "Name") %>
			<%= f.text_field :name, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label(:description, "Description") %>
			<%= f.text_area :description, class: "form-control" %>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-dark">Edit</button>
		</div>

	<% end %>

</div>

app/views/genres/index.html.erb
<div class="container">
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @genres.each do |g| %>
				<tr>
					<td><a href="/genres/<%= g.id %>/songs"><%= g.name %></a></td>
					<td><%= g.description %></td>
					<td><%= link_to 'Edit', edit_genre_path(g), class: "btn btn-dark" %></td>
					<td><%= link_to 'Delete',
						genre_path(g),
						method: :delete,
						data: { confirm: 'Are you sure?' },
						class: "btn btn-dark" 
					%></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/genres/new.html.erb
<div class="container">

	<h5>Create new genre</h5>

	<%= form_with scope: :genre, url: genres_path, local: true do |f| %>

		<div class="form-group">
			<%= f.label(:name, "Name") %>
			<%= f.text_field :name, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label(:description, "Description") %>
			<%= f.text_area :description, class: "form-control" %>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-dark">Create</button>
		</div>

	<% end %>

</div>

app/views/main/index.html.erb
<h1>WELCOME TO POKEDEX</h1>

<%= link_to 'Masters', masters_path %>
<%= link_to 'Pokemons', pokemons_path %>

app/views/songs/edit.html.erb
<div class="container">

	<h5>Edit song</h5>

	<%= form_with model: @song, local: true do |f| %>

		<div class="form-group">
			<%= f.label(:name, "Name") %>
			<%= f.text_field :name, class: "form-control" %>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-dark">Edit</button>
		</div>

	<% end %>

</div>

app/views/songs/index.html.erb
<div class="container">
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Genre</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @songs.each do |s| %>
				<tr>
					<td><%= link_to s.name, song_path(s) %></td>
					<td><%= s.genre.name %></td>
					<td><%= link_to 'Edit', edit_song_path(s), class: "btn btn-dark" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/songs/new.html.erb
<div class="container">

	<h5>Create new song</h5>

	<%= form_with scope: :song, url: songs_path, local: true do |f| %>

		<div class="form-group">
			<%= f.label(:name, "Name") %>
			<%= f.text_field :name, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.collection_select :genre_id, @genres, :id, :name, class: "form-control" %>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-dark">Create</button>
		</div>

	<% end %>

</div>