config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  resources :pokemons do
    resources :masters
  end

  resources :masters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :jobs
    validates :character, presence: true, length: { minimum: 5}
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :song
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :character
end

app/models/master.rb
class Master < ApplicationRecord
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :master
end

app/models/pokemon_master.rb
class PokemonMaster < ApplicationRecord
  has_many :pokemon
end

app/models/pokemonmaster.rb
class Pokemonmaster < ApplicationRecord
  belongs_to :pokemon
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :genre
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def new
    @songs = Song.all
  end

  def create
    @genre = Genre.new(genre_params)

    @genre.save
    redirect_to @genre
  end

  def show
    @genres = Genre.find([params[:id]])
    render "index"
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to @genre
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

private

  def genre_params
    params.require(:genre).permit(:name, :description)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    def create
        @character = Character.find(params[:character_id])
        @job = @character.jobs.create(job_params)
        redirect_to character_path(@character)
    end

    def destroy
        @character = Character.find(params[:character_id])
        @job = @character.jobs.find(params[:id])
        @job.destroy

        redirect_to character_path(@character)
    end

    private
        def job_params
            params.require(:job).permit(:job_name , :job_level , :job_img)
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end

 
end

app/controllers/master_controller.rb
class MasterController < ApplicationController

  def index
    @masters = Master.all
  end

  def new
    @pokemons = Pokemon.all
    #renders new.html.erb in views folder because they have the same name
  end
  
  def show
    @masters = Master.find(params[:id])
    #cases when trying to get a master for the pokemon that does not exist

    if(parmams[:pokemon_id].to_i != @master.pokemon.id)
      puts "master does not exists"
    end
  end

  def create
    @master = Master.new(master_params)

    @master.save
    redirect_to master_index_path
  end

  def update
    @master = Master.find(params[:id])

    @master.update(master_params)
    redirect_to master_index_path

  end

  def edit
    @master = Master.find(params[:id])
    @pokemons = Pokemon.all

  end

  def destroy
    @master = Master.find(params[:id])

    @master.destroy
    redirect_to master_index_path
  end

  private

  def master_params
    params.require(:master).permit(:name, :pokemon_id)
  end

end  

app/controllers/masters_controller.rb
class MastersController < ApplicationController

    def index
        if params.has_key?(:pokemon_id)
            @masters = Master.where(pokemon_id: params[:pokemon_id])
            @pokemon = Pokemon.find(params[:pokemon_id])
        else
            @masters = Master.all.order("id ASC")
        end
    end

    def show
        @master = Master.find(params[:id])
        @pokemon = Pokemon.find(@master[:pokemon_id])
    end

    def new
        @master = Master.new
        @pokemons = Pokemon.all.order("id ASC")
    end

    def create
        @master = Master.create(master_params)
        redirect_to masters_path
	end
	
	def edit
		@master = Master.find(params[:id])
		@pokemons = Pokemon.all.order("id ASC")
	end

	def update
		@master = Master.find(params[:id])
		@master.update(master_params)
		redirect_to @master
	end

	def destroy
		@master = Master.find(params[:id])
		@master.destroy
		redirect_to masters_path
	end
	
    private def master_params
        params.require(:master).permit(:name, :pokemon_id)
    end
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController

  def index
    #this instance variable "SELECT "pokemons".* FROM "pokemons"
    @pokemons = Pokemon.all
  end

  def show
    #  SELECT  "pokemons".* FROM "pokemons" WHERE "pokemons"."id" = $1
    @pokemon = Pokemon.find(params[:id])
  end
  
  def new
  #renders new.html.erb in views folder because they have the same name
  end

  def create
    @pokemons = Pokemon.new(pokemon_params)

    @pokemons.save
    redirect_to pokemon_index_path
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    @pokemon.update(pokemon_params)
    redirect_to pokemon_index_path
  end 
  
  def edit
    @pokemon = Pokemon.find(params[:id])
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])

    @pokemon.destroy
    redirect_to pokemon_index_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:num, :name, :img, :height, :weight, :candy, :candy_count, :egg, :avg_spawns, :spawn_time)
  end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def index
        @pokemons = Pokemon.all.order("id ASC")
    end
    
    def show
        @pokemon = Pokemon.find(params[:id])
    end

    def new
        @pokemon = Pokemon.new
    end

    def create
        @pokemon = Pokemon.create(pokemon_params)
        redirect_to pokemons_path
    end

    def edit
        @pokemon = Pokemon.find(params[:id])
    end

    def update
        @pokemon = Pokemon.find(params[:id])
        @pokemon.update(pokemon_params)
        redirect_to @pokemon
    end
    
    def destroy
        @pokemon = Pokemon.find(params[:id])
        @pokemon.destroy
        redirect_to pokemons_path
    end

    private def pokemon_params
        params.require(:pokemon).permit(:num, :name, :img, :height, :weight)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :find_song, only: [:show, :edit, :update, :destroy]

  def index
    if params.has_key?(:genre_id)
      @songs = Song.where(genre_id: params[:genre_id])
    else
      @songs = Song.all
    end
  end

  def new
    @genres = Genre.all
  end

  def create
    @song = Song.new(song_params)

    @song.save
    redirect_to @song
  end

  def show
    @songs = Song.find([params[:id]])
    render "index"
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to @genre
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path
  end

private

  def song_params
    params.require(:song).permit(:name, :genre_id)
  end

  def find_song
    @song = Song.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/master/edit.html.erb
<h1>Pokedex</h1> 

<p>Update pokemaster</p>

<%= form_with model: @master, local: true do |form| %>
  
  <%= form.collection_select :pokemon_id, @pokemons, :id, :name %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
  <%= form.submit %>
  </p>
    
<% end %>

app/views/master/index.html.erb
<h1>Pokemasters</h1>

Create new pokemaster  <%= link_to 'New', new_master_path%><br>

<table>
  <tr>
    <th>Name</th>
    <th>Pokemon</th>
  </tr>

    <% @masters.each do |master| %>   
        <tr>
            <td><%= master.name %> : </td>
            <td><%= master.pokemon.name %></td>
            <td><%= link_to 'Edit', edit_master_path(master)%></td>
            <td><%= link_to 'Delete', master_path(master), method: :delete %></td>
        </tr>
    <% end %>

</table>

app/views/master/new.html.erb
<h1>Pokedex</h1>

<p>Register new pokemaster</p>

<%= form_with scope: :master, url: master_index_path, local: true do |form| %>
  
  <%= form.collection_select :pokemon_id, @pokemons, :id, :name %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  
  <p>
  <%= form.submit %>
  </p>

<% end %>

app/views/pokemon/edit.html.erb
<h1>Pokedex</h1>

<%= form_with model:@pokemon, url: pokemon_path, local: true do |form| %>
  <p>
    <%= form.label :num %><br>
    <%= form.text_field :num %>
  </p>

  <p>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </p>

  <p>
    <%= form.label :img %><br>
    <%= form.text_area :img %>
  </p>

  <p>
    <%= form.label :height %><br>
    <%= form.text_area :height %>
  </p>

  <p>
    <%= form.label :weight %><br>
    <%= form.text_area :weight %>
  </p>

  <p>
    <%= form.label :candy %><br>
    <%= form.text_area :candy %>
  </p>

  <p>
    <%= form.label :candy_count %><br>
    <%= form.text_area :candy_count %>
  </p>

  <p>
    <%= form.label :egg %><br>
    <%= form.text_area :egg %>
  </p>

  <p>
    <%= form.label :avg_spawns %><br>
    <%= form.text_area :avg_spawns %>
  </p>

  <p>
    <%= form.label :spawn_time %><br>
    <%= form.text_area :spawn_time %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
  
<% end %>

app/views/pokemon/index.html.erb
<h1>Pokedex</h1>

<p>Click here to create a new pokemon <%=link_to 'New', new_pokemon_path %><br></p></br>

<p>Click here to register as a new pokemaster <%= link_to 'New', new_master_path%><br></p></br>

<table>
    <% @pokemons.each do |pokemon| %>
        <tr>
            <td><%= pokemon.num %></td>
            <td><%= pokemon.name %></td>
            <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
            <td><%= link_to 'Delete', pokemon_path(pokemon), method: :delete %></td>
        </tr>
    <% end %>
</table>

app/views/pokemon/new.html.erb
<h1>Pokedex</h1>

<%= form_with scope: :pokemon, url: pokemon_index_path, local: true do |form| %>
    <p>
      <%= form.label :num %><br>
      <%= form.text_field :num %>
    </p>
  
    <p>
      <%= form.label :name %><br>
      <%= form.text_area :name %>
    </p>

    <p>
      <%= form.label :img %><br>
      <%= form.text_area :img %>
    </p>

    <p>
      <%= form.label :height %><br>
      <%= form.text_area :height %>
    </p>

    <p>
      <%= form.label :weight %><br>
      <%= form.text_area :weight %>
    </p>

    <p>
      <%= form.label :candy %><br>
      <%= form.text_area :candy %>
    </p>

    <p>
    <%= form.label :candy_count %><br>
    <%= form.text_area :candy_count %>
    </p>

    <p>
    <%= form.label :egg %><br>
    <%= form.text_area :egg %>
    </p>

    <p>
    <%= form.label :avg_spawns %><br>
    <%= form.text_area :avg_spawns %>
    </p>

    <p>
    <%= form.label :spawn_time %><br>
    <%= form.text_area :spawn_time %>
    </p>

    <p>
      <%= form.submit %>
    </p>

<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing <%= @pokemon.name %></h1>
<%= form_for :pokemon, url: pokemon_path(@pokemon), method: :put do |f| %>
    <p>
        <%= f.label :num %><br>
        <%= f.text_field :num %>
    </p>
    <p>
        <%= f.label :name%><br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :img %><br>
        <%= f.text_field :img %>
    </p>
    <p>
        <%= f.label :height %><br>
        <%= f.text_field :height %>
    </p>
    <p>
        <%= f.label :weight %><br>
        <%= f.text_field :weight %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/pokemons/index.html.erb
<h1>POKEDEX APP</h1>

<h2><%= link_to "New Pokemon", new_pokemon_path %></h2>
<% @pokemons.each do |pokemon| %>
    <%= link_to pokemon[:name], pokemon_path(pokemon) %></br>
<% end %>

app/views/pokemons/new.html.erb
<h1>Create a new Pokemon</h1>
<%= form_for :pokemon, url: pokemons_path do |f| %>
    <p>
        <%= f.label :num %><br>
        <%= f.text_field :num %>
    </p>
    <p>
        <%= f.label :name%><br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :img %><br>
        <%= f.text_field :img %>
    </p>
    <p>
        <%= f.label :height %><br>
        <%= f.text_field :height %>
    </p>
    <p>
        <%= f.label :weight %><br>
        <%= f.text_field :weight %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/pokemons/show.html.erb
<h1>POKEDEX APP</h1>

<%= image_tag(@pokemon.img, :alt => "IMAGE") %>
<h2><%= @pokemon.name %><h2>
<h2>num: <%= @pokemon.num %></h2>
<h2>height: <%= @pokemon.height %></h2>
<h2>weight: <%= @pokemon.weight %></h2>
<br>
<%= button_to "Edit Pokemon", edit_pokemon_path(@pokemon), method: :get %>
<br>
<%= button_to "Delete Pokemon", pokemon_path(@pokemon), method: :delete, data: {confirm: 'Delete Pokemon?'} %>